In [1]:
from stream_topic.preprocessor.Chinese_config import ChineseConfig
ChineseConfig.set_language("chinese")

In [2]:
from stream_topic.models import KmeansTM,BERTopicTM,CBC,DCTE,NMFTM,SOMTM,CEDC,ETM,LDA,ProdLDA,SOMTM,NSTM,WordCluTM,CTM,TNTM,NeuralLDA,CTMNeg
from stream_topic.utils import TMDataset
#本段落用时9min
dataset = TMDataset(stopwords_path = '/hongyi/stream/stopwords/common_stopwords.txt')# language="chinese"
dataset.fetch_dataset(name = "test", dataset_path = "/hongyi/stream/dataset/paper_data", source = 'local')
dataset.preprocess(model_type="KmeansTM", min_word_length = 1)

2025-03-18 11:24:26.546 | INFO     | stream_topic.utils.dataset:fetch_dataset:119 - Fetching dataset: test
2025-03-18 11:24:26.548 | INFO     | stream_topic.utils.dataset:fetch_dataset:129 - Fetching dataset from local path

1
en
chinese

Building prefix dict from the default dictionary ...                              | 0/19600 [00:00<?, ?it/s]
Loading model from cache /tmp/jieba.cache
Loading model cost 0.516 seconds.
Prefix dict has been built successfully.
Preprocessing documents: 100%|██████████████████████████████████████| 19600/19600 [00:05<00:00, 3770.53it/s]

In [3]:
all_words = [word for tokens in dataset.dataframe['tokens'] for word in tokens]
unique_words_total = len(set(all_words))
print("整个数据集的唯一词总数：", unique_words_total)

KeyError: 'tokens'

In [10]:
word_counts = dataset.dataframe['tokens'].apply(len)
stats = word_counts.describe() 
print("分词统计信息：")
print(stats)

分词统计信息：
count    804708.000000
mean        239.121758
std         174.147700
min           1.000000
25%         109.000000
50%         194.000000
75%         325.000000
max        1141.000000
Name: tokens, dtype: float64

In [ ]:
df = dataset.dataframe
new_df = df[df['text'] != '']
 
# 重置索引 
new_df = new_df.reset_index(drop=True) 
 
# 查看结果 
print("处理后的新数据：")
print(new_df)

In [65]:
model = NMFTM(stopwords_path = '/hongyi/stream/stopwords/common_stopwords.txt')
model.fit(dataset,n_topics=10)
# model = NMFTM(stopwords_path = '/hongyi/stream/stopwords/scu_stopwords.txt')# 
# model.fit(dataset)#

topics = model.get_topics()
print(topics)

2025-03-17 16:48:34.311 | INFO     | stream_topic.models.nmf:fit:173 - --- Training NMFTM topic model ---
2025-03-17 16:48:38.350 | INFO     | stream_topic.models.nmf:_clustering:125 - --- Applying NMF clustering ---
2025-03-17 16:48:46.047 | INFO     | stream_topic.models.nmf:fit:244 - --- Training completed successfully. ---

[['宝宝', '情况', '症状', '注意', '建议', '食物', '医生', '问题', '正常', '睡眠'], ['孩子', '症状', '情况', '咳嗽', '医生', '问题', '建议', '注意', '食物', '帮助'], ['骨折', '愈合', '需要', '恢复', '康复', '治疗', '固定', '进行', '手术', '部位'], ['疼痛', '腰椎间盘', '腰部', '突出', '缓解', '肌肉', '热敷', '姿势', '长时间', '腰椎'], ['手术', '术后', '风险', '需要', '医生', '伤口', '进行', '恢复', '并发症', '费用'], ['情绪', '压力', '心理', '放松', '焦虑', '帮助', '尝试', '方法', '睡眠', '抑郁症'], ['食物', '孕妇', '饮食', '摄入', '食用', '怀孕', '维生素', '胎儿', '富含', '注意'], ['病毒', '新冠', '检测', '感染', '复阳', '隔离', '再次', '乙肝', '传播', '阳性'], ['检查', '前列腺', '性生活', '前列腺炎', '尿液', '精液', '进行', '炎症', '精囊炎', '男性']]

In [5]:
model = NMFTM(stopwords_path = '/hongyi/stream/stopwords/common_stopwords.txt')
model.fit(dataset,n_topics=10)
# model = NMFTM(stopwords_path = '/hongyi/stream/stopwords/scu_stopwords.txt')# 
# model.fit(dataset)#

topics = model.get_topics()
print(topics)

2025-03-17 17:03:28.838 | INFO     | stream_topic.models.nmf:fit:173 - --- Training NMFTM topic model ---
2025-03-17 17:03:32.807 | INFO     | stream_topic.models.nmf:_clustering:125 - --- Applying NMF clustering ---
2025-03-17 17:03:38.793 | INFO     | stream_topic.models.nmf:fit:244 - --- Training completed successfully. ---

[['宝宝', '情况', '症状', '注意', '建议', '食物', '医生', '问题', '正常', '睡眠'], ['孩子', '症状', '情况', '咳嗽', '医生', '问题', '建议', '注意', '食物', '发烧'], ['骨折', '愈合', '需要', '恢复', '康复', '治疗', '固定', '进行', '手术', '部位'], ['疼痛', '腰椎间盘', '腰部', '突出', '缓解', '肌肉', '热敷', '姿势', '长时间', '腰椎'], ['手术', '术后', '风险', '需要', '医生', '进行', '伤口', '恢复', '并发症', '费用'], ['情绪', '压力', '心理', '焦虑', '放松', '帮助', '尝试', '方法', '睡眠', '抑郁症'], ['食物', '孕妇', '饮食', '摄入', '食用', '怀孕', '维生素', '胎儿', '富含', '避免'], ['病毒', '新冠', '检测', '感染', '复阳', '隔离', '再次', '乙肝', '传播', '阳性'], ['检查', '血精', '精液', '性生活', '精囊炎', '前列腺炎', '前列腺', '情况', '症状', '进行']]

In [34]:
import json 
import pandas as pd 
# 打开并读取 JSON 文件 
with open('/hongyi/stream/dataset/CMtMedQA.json',  'r', encoding='utf-8') as file:
    data = json.load(file) 
 
# 将 JSON 数据转换为 DataFrame 
df = pd.DataFrame(data)
def flatten_history(history_list):
    if not isinstance(history_list, list) or len(history_list) == 0:
        return ''
    text_lines = []
    for conversation in history_list:
        for text in conversation:
            if isinstance(text, str):
                text_lines.append(text) 
    return '\n'.join(text_lines)
df['text'] = df['history'].apply(flatten_history)
df2 = df[['cate1','text']]
selected_categories = ['五官科', '传染病科','儿科','内科', '外科', '妇产科','男科', '皮肤科','心理科', '肿瘤科']
df3 = df2[df2['cate1'].isin(selected_categories)]
df3 = df3.rename(columns={'cate1':  'labels'}).reindex(columns=['text', 'labels'])
mask = df3['text'].str.strip()  == ''
df3 = df3[~mask].reset_index(drop=True)
df3 = df3.reset_index(drop=True) 
df3.to_csv('/hongyi/stream/dataset/paper_data/CMtMedQA_ten.txt',  sep='\t', index=False, encoding='utf-8')
sampled_df = df3.groupby('labels',  group_keys=False).apply(
    lambda x: x[['text', 'labels']].sample(min(len(x), 1000))
)
sampled_df = sampled_df.reset_index(drop=True) 
sampled_df.to_csv('/hongyi/stream/dataset/paper_data/CMtMedQA_small.txt',  sep='\t', index=False, encoding='utf-8')

In [164]:
import pandas as pd

# 读取文件并加载为 DataFrame
df = pd.read_csv('/hongyi/stream/dataset/paper_data/fudan_cleaned.txt', sep='\t', header=None, names=['text','labels'])
# df = pd.read_csv('/hongyi/stream/dataset/paper_data/Toutiao_long.txt',  sep='\t', encoding='utf-8')
# 查看结果
print(df.head())

                                                text    labels
0  江泽民总书记最近多次指出：“必须高度重视党的思想政治建设，大力提高干部和党员队伍的思想政治素...  Politics
1  巴巴多斯总理抵京开始访华 新华社北京５月９日电应国务院总理李鹏的邀请，巴          ...  Politics
2  新华社北京7月10日电  解放军总政治部、中央军委纪委最近发出通知，向全军转发了兰州军区某团...  Politics
3  江泽民同志在党的十五大报告中明确指出：“在社会主义初级阶段，围绕发展社会生产力这个根本任务，...  Politics
4  〔分类号〕B03    文献标识码：A  文章编号：1003—5281 （2000）03—0...  Politics

In [165]:
word_counts = df['text'].apply(len)
stats = word_counts.describe() 
print("分词统计信息：")
print(stats)

分词统计信息：
count    19614.000000
mean      5458.763026
std       3955.623448
min          5.000000
25%       2507.750000
50%       5130.000000
75%       7531.500000
max      47480.000000
Name: text, dtype: float64

In [166]:
mask = (word_counts >= 50) & (word_counts <= 5000)
new_df = df[mask].copy()

In [167]:
word_counts = new_df['text'].apply(len)
stats = word_counts.describe() 
print("分词统计信息：")
print(stats)

分词统计信息：
count    9540.000000
mean     2379.931132
std      1579.848780
min        51.000000
25%       737.250000
50%      2388.000000
75%      3839.000000
max      5000.000000
Name: text, dtype: float64

In [168]:
new_df.to_csv('/hongyi/stream/dataset/paper_data/fudan_short.txt',  sep='\t', index=False, encoding='utf-8')

In [162]:
sampled_df = df.groupby('labels',  group_keys=False).apply(
    lambda x: x[['text', 'labels']].sample(min(len(x), 1400))
)
sampled_df = sampled_df.reset_index(drop=True) 
sampled_df
sampled_df.to_csv('/hongyi/stream/dataset/paper_data/Toutiao_small.txt',  sep='\t', index=False, encoding='utf-8')

/tmp/ipykernel_817402/1402188512.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_df = df.groupby('labels',  group_keys=False).apply(

In [107]:
sampled_df

                                                    text labels
0      张亚东：世锦赛超奥运没问题 中国游泳已到腾飞时 　　新浪体育讯　4月12日晚，中国泳军在为期...     体育
1      中国军团14大项0金进账 三项亚运金牌数少于奥运 　　新浪体育讯　中国军团在本届亚运会上共夺...     体育
2      本菲卡觅得科恩特朗替身 宣布与西班牙国脚签约两年  　　新浪体育讯　北京时间7月21日消息，...     体育
3      命脉人物称伊布难离国米 防线大将告别蓝黑军提前宣布 　　新浪体育讯　伊布的去留风波炒了几天，...     体育
4      无唐江苏谁是真核心 胡雪峰得分之外还有可怕之处 　　本报记者阿笨报道 一直以来，胡雪峰都是球...     体育
...                                                  ...    ...
13995  指基发行退潮 ETF逆势井喷 　　□本报记者 余? 北京报道 　　经历了2009年的发行“大...     财经
13996  500万吨最低价小麦入市遇冷 稳定麦价效果初现 　　胡军华 　　因终端面粉、麸皮等需求不旺，...     财经
13997  上期所输出中国标准见成效 　　已注册的境外品牌铜升至25个 　　证券时报记者 游 石 　　本...     财经
13998  金价距离历史高点7% 多数投资者短线看空黄金 　　自从09年12月份创出历史纪录后，黄金价格...     财经
13999  原油市场将继续跟随中东及北非地区形势的发展 　　以下为南非标准银行(Standard Ban...     财经

[14000 rows x 2 columns]

In [108]:
word_counts = sampled_df['text'].apply(len)
stats = word_counts.describe() 
print("分词统计信息：")
print(stats)

分词统计信息：
count    14000.000000
mean       816.201643
std        619.065411
min         50.000000
25%        347.000000
50%        653.000000
75%       1131.000000
max       2998.000000
Name: text, dtype: float64

In [1]:
import pandas as pd
df = pd.read_csv('/hongyi/stream/dataset/paper_data/CMtMedQA_small.txt',  sep='\t', encoding='utf-8')
df

                                                   text labels
0     我最近得了青光眼，我想知道是否能继续抽烟？\n青光眼是一种会导致视乳头萎缩及凹陷、视野缺损及...    五官科
1     最近工作很忙，一直都在熬夜，导致我的眼睛非常不舒服，还出现了血丝。请问眼白上出现的血丝要多久...    五官科
2     医生，我每次刷牙的时候都会感到一些酸痛，这是为什么呢？\n您好！刷牙时感到酸痛可能是因为您的...    五官科
3     你好，忽然不能说出来话了，就是发现嗓子哑了，请问嗓子哑了这是怎么了？\n你好，嗓子哑了可能是...    五官科
4     你好，我是牙齿有牙结石，打算进行洗牙，请问洗牙后可以喝酒吗？我是男性，29岁。\n您好！洗牙...    五官科
...                                                 ...    ...
9904  医生您好，我患有癌症，但是怀孕了，请问癌症遗传概率有多大？该怎么办？[女 26岁]\n您好，...    肿瘤科
9905  我连续便血两周了，腹部疼痛的厉害，去医院检查是直肠癌，这种病是不是很严重，平时饮食要注意什么...    肿瘤科
9906  我妈十年前因子宫手术后得了淋巴水肿，去年的了淋巴管肉瘤，有什么靶向药可以一试？女，75岁\n...    肿瘤科
9907  最近我经常感觉心绞痛，去医院检查结果显示癌胚抗原阳性，不知道这个是什么意思？是癌症吗？\n您...    肿瘤科
9908  医生您好，我患有淋巴瘤，长在脖子位置，听说还有其他位置，请问淋巴肿瘤一般长在哪里？该怎么治疗...    肿瘤科

[9909 rows x 2 columns]

In [2]:
#本段落用时9min
from stream_topic.utils.dataset import TMDataset

# 创建 TMDataset 实例
dataset = TMDataset()#language="zh-cn", stopwords_path = '/hongyi/stream/stopwords/baidu_stopwords.txt'

# 假设你有一个名为 df 的 DataFrame，包含你的数据
# df = pd.DataFrame(...)

# 数据集名称
dataset_name = "test"

# 指定保存数据集的目录
save_dir = "/hongyi/stream/dataset/paper_data"
# df = df.iloc[0:10]
# 调用 create_load_save_dataset 方法来存储数据集
dataset.create_load_save_dataset(
    data=df,
    dataset_name=dataset_name,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    save_dir=save_dir,
    doc_column="text",  # 假设 DataFrame 中包含文本的列名为 "text_column"
    label_column="labels",  # 假设 DataFrame 中包含标签的列名为 "label_column"
    language = "chinese",
    stopwords_path = '/hongyi/stream/stopwords/common_stopwords.txt',
    min_word_length = 1,
    min_word_freq = 5,
    segmentation_tool = 'pkuseg',
    # domain = 'medicine'
)

# 打印保存的数据集信息
print(dataset.dataframe.head())

5

Preprocessing documents: 100%|████████████████████████████████████████████████████████████████████████████████| 9909/9909 [4:45:46<00:00,  1.73s/it]
2025-03-18 21:22:54.191 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:242 - Dataset saved to /hongyi/stream/dataset/paper_data/test.parquet
2025-03-18 21:22:54.202 | INFO     | stream_topic.utils.dataset:create_load_save_dataset:259 - Dataset info saved to /hongyi/stream/dataset/paper_data/test_info.pkl

  language                                 stopwords_path  min_word_length  \
0  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1
1  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1
2  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1
3  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1
4  chinese  /hongyi/stream/stopwords/common_stopwords.txt                1

   min_word_freq segmentation_tool  \
0              5            pkuseg
1              5            pkuseg
2              5            pkuseg
3              5            pkuseg
4              5            pkuseg

                                                text labels
0  青光眼 抽烟 青光眼 会 抽烟 青光眼 会 抽烟 青光眼 抽烟 青光眼 抽烟 会 抽烟 会 ...    五官科
1  导致 眼睛 血丝 血丝 会 眼睛 血丝 血丝 会 症状 会 症状 眼睛 眼睛 眼睛 眼睛 症...    五官科
2  刷牙 刷牙 牙齿 蛀牙 蛀牙 牙齿 问题 牙齿 牙齿 导致 牙齿 蛀牙 问题 刷牙 刷牙 刷...    五官科
3  不 嗓子 哑 嗓子 哑 嗓子 哑 感觉 嗓子 感觉 嗓子 感觉 嗓子 嗓子 哑 还 声带 进...    五官科
4  牙齿 进行 洗牙 洗牙 后 好 洗牙 口腔 洗牙 后 建议 洗牙 后 避免 洗牙 过程 中 ...    五官科